Updated management commands.

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Run the production server
 
@@ -7,20 +7,28 @@
 #
 
 log() {
-	if [ -t 2 ]; then
-		C0='\033[0m'
-		C1='\033[31m'
-		C2='\033[32m'
-		C3='\033[33m'
-		C4='\033[34m'
-		C5='\033[35m'
-		CB='\033[1m'
+	if [[ -t 2 ]]; then
+		local C0=$'\033[0m'
+		local C1=$'\033[31m'
+		local C2=$'\033[32m'
+		local C3=$'\033[33m'
+		local C4=$'\033[34m'
+		local C5=$'\033[35m'
+		local CB=$'\033[1m'
 	fi
-	n="${C0}"
-	c="${C4}"
-	p='*'
-	while getopts ":eswd" opt; do
+
+	local n="${C0}"
+	local c="${C4}"
+	local p='*'
+	local e=
+
+	while getopts ":ceswd" opt; do
 		case "${opt}" in
+			c)
+				p='✖'
+				c="${C1}"
+				e=1
+				;;
 			e)
 				p='✖'
 				c="${C1}"
@@ -41,8 +49,13 @@ log() {
 		esac
 	done
 	shift $((OPTIND - 1))
+	unset OPTIND
 
 	printf "${n}[${CB}${c}${p}${n}] ${NAME}: %s\n" "${*}" >&2
+
+	if [[ ${e} ]]; then
+		exit 1
+	fi
 }
 
 usage() {
@@ -58,7 +71,6 @@ BASE="$(realpath "$(dirname "${0}")"/..)"
 
 ADDR=0.0.0.0
 PORT=1080
-
 SOCKET=
 
 USAGE="\
@@ -76,9 +88,15 @@ Extra arguments are sent to the server."
 
 while getopts ":H:P:S:h" opt; do
 	case "${opt}" in
-		H) ADDR="${OPTARG}" ;;
-		P) PORT="${OPTARG}" ;;
-		S) SOCKET="$(realpath -m "${OPTARG}")" ;;
+		H)
+			ADDR="${OPTARG}"
+			;;
+		P)
+			PORT="${OPTARG}"
+			;;
+		S)
+			SOCKET="$(realpath -m "${OPTARG}")"
+			;;
 		h)
 			usage
 			exit
@@ -95,41 +113,38 @@ while getopts ":H:P:S:h" opt; do
 	esac
 done
 shift $((OPTIND - 1))
+unset OPTIND
 
 log "Initializing virtual environment."
 
-if [ -d "${BASE}"/.venv ] && [ -f "${BASE}"/.venv/bin/activate ]; then
+if [[ -d ${BASE}/.venv && -f ${BASE}/.venv/bin/activate ]]; then
 	. "${BASE}"/.venv/bin/activate
 else
 	log -w "No virtual environment found!"
 fi
 
-if ! command -v python3 >/dev/null 2>&1; then
-	log -e "Python3 not installed!"
-	exit 1
+if ! command -v gunicorn &>/dev/null; then
+	log -c "gunicorn is not installed!"
 fi
 
-if ! command -v gunicorn >/dev/null 2>&1; then
-	log -e "Server (gunicorn) not found!"
-	exit 1
-fi
-
-if ! cd "${BASE}" >/dev/null 2>&1; then
-	log -e "Failed to switch to project directory!"
-	exit 1
+if ! cd "${BASE}" &>/dev/null; then
+	log -c "Failed to change to project directory!"
 fi
 
 log "Starting the production server."
 
-if [ -n "${SOCKET}" ]; then
+if [[ ${SOCKET} ]]; then
 	BIND="unix:${SOCKET}"
-	log "Listening at: ${SOCKET}"
+
+	log "Listening at: ${SOCKET#"${BASE}"/}"
 else
 	BIND="${ADDR}:${PORT}"
+
 	log "Listening at: http://${ADDR}:${PORT}"
 fi
 
 exec gunicorn \
-	-w "$(nproc || printf 1)" \
-	-b "${BIND}" \
-	'app:create_app()' "${@}" >/dev/null 2>&1
+	--bind "${BIND}" \
+	--workers "$(nproc || printf 1)" \
+	--keep-alive 60 \
+	'app:create_app()' "${@}" &>/dev/null
diff --git a/bin/run-dev b/bin/run-dev
--- a/bin/run-dev
+++ b/bin/run-dev
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Run the development server
 
@@ -7,20 +7,28 @@
 #
 
 log() {
-	if [ -t 2 ]; then
-		C0='\033[0m'
-		C1='\033[31m'
-		C2='\033[32m'
-		C3='\033[33m'
-		C4='\033[34m'
-		C5='\033[35m'
-		CB='\033[1m'
+	if [[ -t 2 ]]; then
+		local C0=$'\033[0m'
+		local C1=$'\033[31m'
+		local C2=$'\033[32m'
+		local C3=$'\033[33m'
+		local C4=$'\033[34m'
+		local C5=$'\033[35m'
+		local CB=$'\033[1m'
 	fi
-	n="${C0}"
-	c="${C4}"
-	p='*'
-	while getopts ":eswd" opt; do
+
+	local n="${C0}"
+	local c="${C4}"
+	local p='*'
+	local e=
+
+	while getopts ":ceswd" opt; do
 		case "${opt}" in
+			c)
+				p='✖'
+				c="${C1}"
+				e=1
+				;;
 			e)
 				p='✖'
 				c="${C1}"
@@ -41,8 +49,13 @@ log() {
 		esac
 	done
 	shift $((OPTIND - 1))
+	unset OPTIND
 
 	printf "${n}[${CB}${c}${p}${n}] ${NAME}: %s\n" "${*}" >&2
+
+	if [[ ${e} ]]; then
+		exit 1
+	fi
 }
 
 usage() {
@@ -58,43 +71,40 @@ BASE="$(realpath "$(dirname "${0}")"/..)"
 
 log "Initializing virtual environment."
 
-if [ -d "${BASE}"/.venv ] && [ -f "${BASE}"/.venv/bin/activate ]; then
+if [[ -d ${BASE}/.venv && -f ${BASE}/.venv/bin/activate ]]; then
 	. "${BASE}"/.venv/bin/activate
 else
 	log -w "No virtual environment found!"
 fi
 
-if ! command -v python3 >/dev/null 2>&1; then
-	log -e "Python3 not installed!"
-	exit 1
-fi
+for cmd in dotenv flask; do
+	if ! command -v "${cmd}" &>/dev/null; then
+		log -c "${cmd} is not installed!"
+	fi
+done
 
-if ! command -v flask >/dev/null 2>&1; then
-	log -e "Server (flask) not found!"
-	exit 1
-fi
-
-if ! command -v dotenv >/dev/null 2>&1; then
-	log -e "dotenv command not found!"
-	exit 1
-fi
-
-if ! cd "${BASE}" >/dev/null 2>&1; then
-	log -e "Failed to switch to project directory!"
-	exit 1
+if ! cd "${BASE}" &>/dev/null; then
+	log -c "Failed to change to project directory!"
 fi
 
 log "Initializing environment variables."
 
-if [ -f .env ]; then
-	CACHE_DIR="$(dotenv get CACHE_DIR 2>/dev/null)"
-	MANIFEST_FILE="$(dotenv get MANIFEST_FILE 2>/dev/null)"
+if [[ -f .env ]]; then
+	eval "$(dotenv list --format shell | grep -e ^CACHE_DIR -e ^MANIFEST_FILE)"
+
+	for var in CACHE_DIR MANIFEST_FILE; do
+		if [[ ! "${!var}" ]]; then
+			log -c "Variable ${var} is not set!"
+		fi
+	done
 else
-	log -e ".env file not found!"
-	exit 1
+	log -c ".env file not found!"
 fi
 
 log "Starting the development server."
 
-exec flask run --debug --host 0.0.0.0 --port 5000 \
+exec flask run \
+	--debug \
+	--host 0.0.0.0 \
+	--port 5000 \
 	--extra-files "${CACHE_DIR:-.}/${MANIFEST_FILE:-manifest.json}" "${@}"
diff --git a/bin/update-cache b/bin/update-cache
--- a/bin/update-cache
+++ b/bin/update-cache
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Update the cache files
 
@@ -7,20 +7,28 @@
 #
 
 log() {
-	if [ -t 2 ]; then
-		C0='\033[0m'
-		C1='\033[31m'
-		C2='\033[32m'
-		C3='\033[33m'
-		C4='\033[34m'
-		C5='\033[35m'
-		CB='\033[1m'
+	if [[ -t 2 ]]; then
+		local C0=$'\033[0m'
+		local C1=$'\033[31m'
+		local C2=$'\033[32m'
+		local C3=$'\033[33m'
+		local C4=$'\033[34m'
+		local C5=$'\033[35m'
+		local CB=$'\033[1m'
 	fi
-	n="${C0}"
-	c="${C4}"
-	p='*'
-	while getopts ":eswd" opt; do
+
+	local n="${C0}"
+	local c="${C4}"
+	local p='*'
+	local e=
+
+	while getopts ":ceswd" opt; do
 		case "${opt}" in
+			c)
+				p='✖'
+				c="${C1}"
+				e=1
+				;;
 			e)
 				p='✖'
 				c="${C1}"
@@ -41,8 +49,13 @@ log() {
 		esac
 	done
 	shift $((OPTIND - 1))
+	unset OPTIND
 
 	printf "${n}[${CB}${c}${p}${n}] ${NAME}: %s\n" "${*}" >&2
+
+	if [[ ${e} ]]; then
+		exit 1
+	fi
 }
 
 usage() {
@@ -55,20 +68,33 @@ usage() {
 
 NAME="$(basename "${0}")"
 BASE="$(realpath "$(dirname "${0}")"/..)"
-PID=
+
+IMAGES=1
+VIDEOS=1
+PID=()
 
 USAGE="\
-Usage: ${NAME} [OPTION]
+Usage: ${NAME} [OPTION] [PATH]...
 
 Update the cache files.
 
 Options:
+  -i        Generate image thumbnails only.
+  -v        Generate video thumbnails only.
   -p <PID>  Reload a running server.
   -h        Show help message and exit."
 
-while getopts ":p:h" opt; do
+while getopts ":ivp:h" opt; do
 	case "${opt}" in
-		p) PID="${OPTARG}" ;;
+		i)
+			VIDEOS=
+			;;
+		v)
+			IMAGES=
+			;;
+		p)
+			PID+=("${OPTARG}")
+			;;
 		h)
 			usage
 			exit
@@ -86,95 +112,124 @@ while getopts ":p:h" opt; do
 	esac
 done
 shift $((OPTIND - 1))
+unset OPTIND
 
 log "Initializing virtual environment."
 
-if [ -d "${BASE}"/.venv ] && [ -f "${BASE}"/.venv/bin/activate ]; then
+if [[ -d ${BASE}/.venv && -f ${BASE}/.venv/bin/activate ]]; then
 	. "${BASE}"/.venv/bin/activate
 else
 	log -w "No virtual environment found!"
 fi
 
-for cmd in dotenv convert ffmpeg; do
-	if ! command -v "${cmd}" >/dev/null 2>&1; then
-		log -e "${cmd} not installed!"
-		exit 1
+for cmd in dotenv magick ffmpeg; do
+	if ! command -v "${cmd}" &>/dev/null; then
+		log -c "${cmd} is not installed!"
 	fi
 done
 
-if ! cd "${BASE}" >/dev/null 2>&1; then
-	log -e "Failed to switch to project directory!"
-	exit 1
+if ! cd "${BASE}" &>/dev/null; then
+	log -c "Failed to change to project directory!"
 fi
 
 log "Initializing environment variables."
 
-if [ -f .env ]; then
-	MEDIA_DIR=$(dotenv get MEDIA_DIR)
-	IMAGE_EXTS=$(dotenv get IMAGE_EXTS)
-	VIDEO_EXTS=$(dotenv get VIDEO_EXTS)
-	CACHE_DIR=$(dotenv get CACHE_DIR)
-	THUMBNAILS_FILE=$(dotenv get THUMBNAILS_FILE)
-	THUMBNAILS_EXT=$(dotenv get THUMBNAILS_EXT)
+if [[ -f .env ]]; then
+	eval "$(dotenv list --format shell | grep -e ^MEDIA_DIR -e ^IMAGE_EXTS -e ^VIDEO_EXTS -e ^CACHE_DIR -e ^THUMBNAILS_FILE -e ^THUMBNAILS_EXT)"
+
+	for var in MEDIA_DIR IMAGE_EXTS VIDEO_EXTS CACHE_DIR THUMBNAILS_FILE THUMBNAILS_EXT; do
+		if [[ ! "${!var}" ]]; then
+			log -c "Variable ${var} is not set!"
+		fi
+	done
 else
-	log -e ".env file not found!"
-	exit 1
+	log -c ".env file not found!"
+fi
+
+FIND_DIRS=()
+MEDIA_DIR=$(realpath -sm "${MEDIA_DIR}")
+
+if [[ ${#} -gt 0 ]]; then
+	for dir in "${@}"; do
+		target=$(realpath -sm "${dir}")
+
+		if [[ ${target:0:${#MEDIA_DIR}} == "${MEDIA_DIR}" ]]; then
+			FIND_DIRS+=("${target}")
+		else
+			log -c "${dir} is not within the media directory."
+		fi
+	done
+else
+	FIND_DIRS+=("${MEDIA_DIR}"/)
 fi
 
 log "Preparing cache directory."
 
 if ! mkdir -p "${CACHE_DIR}/${THUMBNAILS_FILE}"; then
-	log -e "Failed to prepare cache directory."
-	exit 1
+	log -c "Failed to prepare cache directory."
 fi
 
-log "Generating image thumbnails."
+if [[ ${IMAGES} ]]; then
+	log "Generating image thumbnails."
 
-for img in $(eval "find \"${MEDIA_DIR}\"/ -iname *$(printf %s "${IMAGE_EXTS}" | sed -E 's/,/ -o -iname */g') -type f,l"); do
-	thumb=$(printf %s "${CACHE_DIR}/${THUMBNAILS_FILE}/${img}" | sed -E "s/${MEDIA_DIR}\///; s/\.[a-zA-Z0-9]+$/${THUMBNAILS_EXT}/")
+	eval "find \"\${FIND_DIRS[@]}\" \( -iname \*${IMAGE_EXTS//,/ -o -iname *} -type f,l \) -print0" | while IFS= read -r -d '' img; do
+		file="${img#"${MEDIA_DIR}"/}"
+		thumb="${CACHE_DIR}/${THUMBNAILS_FILE}/${file%.*}${THUMBNAILS_EXT}"
 
-	if mkdir -p "$(dirname "${thumb}")" &&
-		convert "${img}" -resize 320x -quality 70 "${thumb}"; then
-		log -s "${img}"
-	else
-		log -e "${img}"
-	fi
-done
+		if [[ -f "${thumb}" ]]; then
+			continue
+		fi
 
-log "Generating video thumbnails."
+		if mkdir -p "$(dirname "${thumb}")" && magick "${img}"[0] -resize 320x -quality 70 "${thumb}"; then
+			log -s "${file}"
+		else
+			log -e "${file}"
+		fi
+	done
+fi
 
-for vid in $(eval "find \"${MEDIA_DIR}\"/ -iname *$(printf %s "${VIDEO_EXTS}" | sed -E "s/,/ -o -iname */g") -type f,l"); do
-	thumb=$(printf %s "${CACHE_DIR}/${THUMBNAILS_FILE}/${vid}" | sed -E "s/${MEDIA_DIR}\///; s/\.[a-zA-Z0-9]+$/${THUMBNAILS_EXT}/")
+if [[ ${VIDEOS} ]]; then
+	log "Generating video thumbnails."
 
-	duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${vid}" | cut -d. -f1)
-	if [ -z "${duration}" ]; then
-		log -e "${vid}"
-		continue
-	fi
+	eval "find \"\${FIND_DIRS[@]}\" \( -iname \*${VIDEO_EXTS//,/ -o -iname *} -type f,l \) -print0" | while IFS= read -r -d '' vid; do
+		file="${vid#"${MEDIA_DIR}"/}"
+		thumb="${CACHE_DIR}/${THUMBNAILS_FILE}/${file%.*}${THUMBNAILS_EXT}"
 
-	seek=$(echo "scale=0; ${duration} * 0.1 / 1" | bc)
-	if [ "${seek}" -le 0 ]; then
-		seek=1
-	fi
+		if [[ -f "${thumb}" ]]; then
+			continue
+		fi
 
-	if mkdir -p "$(dirname "${thumb}")" &&
-		ffmpeg -n -ss "${seek}" -i "${vid}" -vf scale=320:-1 -q:v 7 -frames:v 1 "${thumb}" >/dev/null 2>&1; then
-		log -s "${vid}"
-	else
-		log -e "${vid}"
-	fi
-done
+		duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${vid}" | cut -d. -f1)
+
+		if [[ ! ${duration} || ${duration} -lt 1 ]]; then
+			log -e "${file}"
+			continue
+		fi
+
+		seek=$(echo "scale=0; ${duration} * 10 / 100" | bc)
+
+		if [[ "${seek}" -le 0 ]]; then
+			seek=1
+		fi
+
+		if mkdir -p "$(dirname "${thumb}")" && { ffmpeg -n -nostdin -ss "${seek}" -i "${vid}" -vf "select=eq(pict_type\,I),scale=320:-1" -frames:v 1 -q:v 5 "${thumb}" || ffmpeg -n -nostdin -ss "${seek}" -i "${vid}" -vf "scale=320:-1" -frames:v 1 -q:v 5 "${thumb}"; } &>/dev/null; then
+			log -s "${file}"
+		else
+			log -e "${file}"
+		fi
+	done
+fi
 
 log "Updating the manifest file."
 
-if bin/update-manifest >/dev/null 2>&1; then
+if bash bin/update-manifest &>/dev/null; then
 	log -s "Manifest file updated succesfully!"
 else
-	log -e "Failed to update the manifest file."
-	exit 1
+	log -c "Failed to update the manifest file."
 fi
 
-if [ -n "${PID}" ]; then
+if [[ ${#PID} -gt 0 ]]; then
 	log "Reloading running servers."
-	bin/reload-server "${PID}"
+
+	bash bin/reload-server "${PID[@]}"
 fi
diff --git a/bin/update-manifest b/bin/update-manifest
--- a/bin/update-manifest
+++ b/bin/update-manifest
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Update the manifest file
 
@@ -7,20 +7,28 @@
 #
 
 log() {
-	if [ -t 2 ]; then
-		C0='\033[0m'
-		C1='\033[31m'
-		C2='\033[32m'
-		C3='\033[33m'
-		C4='\033[34m'
-		C5='\033[35m'
-		CB='\033[1m'
+	if [[ -t 2 ]]; then
+		local C0=$'\033[0m'
+		local C1=$'\033[31m'
+		local C2=$'\033[32m'
+		local C3=$'\033[33m'
+		local C4=$'\033[34m'
+		local C5=$'\033[35m'
+		local CB=$'\033[1m'
 	fi
-	n="${C0}"
-	c="${C4}"
-	p='*'
-	while getopts ":eswd" opt; do
+
+	local n="${C0}"
+	local c="${C4}"
+	local p='*'
+	local e=
+
+	while getopts ":ceswd" opt; do
 		case "${opt}" in
+			c)
+				p='✖'
+				c="${C1}"
+				e=1
+				;;
 			e)
 				p='✖'
 				c="${C1}"
@@ -41,8 +49,13 @@ log() {
 		esac
 	done
 	shift $((OPTIND - 1))
+	unset OPTIND
 
 	printf "${n}[${CB}${c}${p}${n}] ${NAME}: %s\n" "${*}" >&2
+
+	if [[ ${e} ]]; then
+		exit 1
+	fi
 }
 
 usage() {
@@ -55,7 +68,8 @@ usage() {
 
 NAME="$(basename "${0}")"
 BASE="$(realpath "$(dirname "${0}")"/..)"
-PID=
+
+PID=()
 
 USAGE="\
 Usage: ${NAME} [OPTION]
@@ -68,7 +82,9 @@ Options:
 
 while getopts ":p:h" opt; do
 	case "${opt}" in
-		p) PID="${OPTARG}" ;;
+		p)
+			PID+=("${OPTARG}")
+			;;
 		h)
 			usage
 			exit
@@ -86,35 +102,34 @@ while getopts ":p:h" opt; do
 	esac
 done
 shift $((OPTIND - 1))
+unset OPTIND
 
 log "Initializing virtual environment."
 
-if [ -d "${BASE}"/.venv ] && [ -f "${BASE}"/.venv/bin/activate ]; then
+if [[ -d ${BASE}/.venv && -f ${BASE}/.venv/bin/activate ]]; then
 	. "${BASE}"/.venv/bin/activate
 else
 	log -w "No virtual environment found!"
 fi
 
-if ! command -v python3 >/dev/null 2>&1; then
-	log -e "Python3 not installed!"
-	exit 1
+if ! command -v python3 &>/dev/null; then
+	log -c "python3 is not installed!"
 fi
 
-if ! cd "${BASE}" >/dev/null 2>&1; then
-	log -e "Failed to switch to project directory!"
-	exit 1
+if ! cd "${BASE}" &>/dev/null; then
+	log -c "Failed to change to project directory!"
 fi
 
 log "Updating the manifest file."
 
-if python3 -B -m app.manifest >/dev/null 2>&1; then
+if python3 -B -m app.manifest &>/dev/null; then
 	log -s "Manifest file updated succesfully!"
 else
-	log -e "Failed to update the manifest file."
-	exit 1
+	log -c "Failed to update the manifest file."
 fi
 
-if [ -n "${PID}" ]; then
+if [[ ${#PID} -gt 0 ]]; then
 	log "Reloading running servers."
-	bin/reload-server "${PID}" >/dev/null 2>&1
+
+	bash bin/reload-server "${PID[@]}"
 fi
